#ifndef __ENUM_H__
#define __ENUM_H__

enum OBJ_TYPE{
	OBJ_MAP ,OBJ_ALLIED, OBJ_ENEMY, OBJ_VEHICLE ,OBJ_USEOBJ ,OBJ_MAPOBJ, OBJ_EFFECT ,OBJ_UI, OBJ_END
};

enum UNIT_TYPE{
	UNIT_MULTISELECT = -1 , UNIT_GREENBERETS, UNIT_MARINE, UNIT_DRIVER, UNIT_END
};

enum SCENE_TYPE{
	SCENE_TITLE, SCENE_MENU, SCENE_MISSION_01, SCENE_CLEAR
};

enum ANGLE_TYPE{
	ANGLE_RIGHT, ANGLE_RDOWN, ANGLE_DOWN, ANGLE_UP, ANGLE_RUP,
	ANGLE_LEFT, ANGLE_LDOWN, ANGLE_LUP
};

enum STATE_TYPE{
	STATE_STAND, STATE_WALK, STATE_RUN, STATE_PRONE, STATE_KNIFE, STATE_GUN, STATE_DEAD, STATE_CARRYBODY, STATE_CARRY
	, STATE_HARPOON, STATE_DIVE, STATE_LADDER, STATE_LADDEREND, STATE_VEHICLE
};

enum SKILL_TYPE{
	SKILL_NULL = -1, SKILL_KNIFE, SKILL_GUN, SKILL_CARRYBODY, SKILL_CARRY, SKILL_HARPOON, SKILL_LADDER, SKILL_VEHICLE
};

enum RENDER_LAYER{
	RENDER_BACKGRUOND, RENDER_DEADOBJECT , RENDER_GAMEOBJECT, RENDER_EFFECT, RENDER_UI, RENDER_END
};

enum TILE_TYPE{
	 TILE_NULL, TILE_OBJ, TILE_HOUSE ,TILE_WATER, TILE_DWATER, TILE_WALL
};

enum BUILDING_TYPE{
	BUILDING_ONE, BUILDING_TWO, BUILDING_THREE
};

enum EFFECT_TYPE{
	EFFECT_PISTOL, EFFECT_EXPLOSION, EFFECT_FIRE,  EFFECT_BLOOD, EFFECT_MOVE
};

enum UI_STAND_PRONE{
	UI_PRONE, UI_STAND, UI_STAND_PROEN_END
};

enum UI_BUTTON{
	UI_PISTOL, UI_SMG, UI_CARRY, UI_KNIFE, UI_BOAT, UI_HARPOON, UI_DIVE, UI_PICTURE , UI_BUTTON_END
};

enum UNIT_SOUND{
	SOUND_MOVE, SOUND_REFUSE, SOUND_ATTACK, SOUND_ACTION, SOUND_END
};

enum MOUSE_ENUM{
	MOUSE_DEFAULT, MOUSE_PISTOL, MOUSE_N_PISTOL,MOUSE_KNIFE, MOUSE_N_KNIFE, MOUSE_CARRY, MOUSE_N_CARRY
};

#endif // !__ENUM_H__
